# Generated by Django 5.1 on 2024-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='user_phone_number', max_length=12, unique=True),
        ),
    ]
